# Generated by Django 4.2.4 on 2023-08-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_task_end_date_alter_task_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todo_app.notes', verbose_name='Родитель'),
        ),
    ]
